#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec  1 07:57:13 2021

@author: jason

This dataset provides daily estimates of global sea surface temperature (SST) based on observations from multiple satellite sensors since September 1981. SST is known to be a significant driver of global weather and climate patterns and to play important roles in the exchanges of energy, momentum, moisture and gases between the ocean and atmosphere. As such, its knowledge is essential to understand and assess variability and long-term changes in the Earth’s climate.

The SST data provided here are based on measurements carried out by the following infrared sensors flown onboard multiple polar-orbiting satellites: the series of Advanced Very High Resolution Radiometers (AVHRRs), the series of Along Track Scanning Radiometers (ATSRs), and the Sea and Land Surface Temperature Radiometer (SLSTR).

The dataset provides SST products of different processing levels. Only Level-3 Collated and Level-4 and served through this entry in the Catalogue. Due to the large number of files at Level-2 Pre-processed and Level-3 Collated these products are served through the Climate Data Store API. For more information on how to access these levels consult the documentation.

The four types of products are:

Level-2 Pre-processed (L2P): SST data on the native satellite swath grid and derived from single-sensor measurements.
Level-3 Uncollated (L3U): SST product generated by regridding L2P data onto a global latitude-longitude grid.
Level-3 Collated (L3C): global daily (day and night) single-sensor SST product based on collated L3U data.
Level-4 (L4): spatially complete global SST product based on data from multiple sensors.
These products are available as Climate Data Records (CDRs), which have sufficient length, consistency, and continuity to be used to assess climate variability and changes. These SST CDRs are identical to those produced as part of the European Space Agency (ESA) SST Climate Change Initiative (CCI) project. Interim CDRs (ICDRs) are produced at levels L3C and L4 on behalf of the Copernicus Climate Change Service (C3S) to extend the baseline CDRs. Both SST CDRs and ICDRs are generated using software and algorithms developed as part of the ESA SST CCI.

Users should use the most recent version of the dataset whenever possible. Data from the previous version are also made available but cover shorter periods.

https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-sea-surface-temperature?tab=overview

"""

import cdsapi

c = cdsapi.Client()

c.retrieve(
    'satellite-sea-surface-temperature',
    {
        'version': '2_1',
        'variable': 'all',
        'format': 'zip',
        'year': [
            '1982', '1983', '1984',
            '1985', '1986', '1987',
            '1988', '1989', '1990',
            '1991', '1992', '1993',
            '1994', '1995', '1996',
            '1997', '1998', '1999',
            '2000', '2001', '2002',
            '2003', '2004', '2005',
            '2006', '2007', '2008',
            '2009', '2010', '2011',
            '2012', '2013', '2014',
            '2015', '2016', '2017',
            '2018', '2019', '2020',
            '2021',
        ],
        'month': '08',
        'day': [
            '13', '14',
        ],
        'processinglevel': 'level_4',
        'sensor_on_satellite': 'combined_product',
    },
    '/Users/jason/0_dat/SST/SST_1982-2021_13-14_August.zip')